"""Disclaimer and license acceptance dialog for KADAS Altair plugin.

Shown when the plugin is activated until the user accepts and chooses
to remember the decision.
"""

from __future__ import annotations

from qgis.PyQt.QtCore import Qt
from qgis.PyQt.QtGui import QFont
from qgis.PyQt.QtWidgets import (
    QCheckBox,
    QDialog,
    QDialogButtonBox,
    QFrame,
    QLabel,
    QTextEdit,
    QVBoxLayout,
)

try:
    from qgis.core import QgsSettings
except ImportError:
    from qgis.PyQt.QtCore import QSettings as QgsSettings


_SETTINGS_KEY = "AltairEOData/disclaimer_accepted"

_DISCLAIMER_TEXT = (
    "<b>LIMITATION OF LIABILITY</b><br><br>"
    "This software is provided for informational and planning purposes only. "
    "Any search, tasking suggestion, geometry, orbit prediction, or output "
    "generated by this plugin must be independently validated before "
    "operational use.<br><br>"
    "The authors, contributors, and distributors of this software expressly "
    "disclaim all liability for any accident, incident, injury, loss, or "
    "damage resulting from misuse or from reliance on plugin outputs.<br><br>"
    "The end user remains solely responsible for lawful and appropriate use "
    "of this software, compliance with applicable regulations, and all "
    "decisions made before, during, and after any operation."
)

_LICENSE_TEXT = """\
MIT License

Copyright (c) 2026 Michael Lanini

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

---

THIRD-PARTY NOTICES

This software makes use of the following open-source projects:

1. QGIS (GPL v2+)
     - https://qgis.org
     - Geographic Information System framework

2. KADAS Albireo (GPL v2+)
     - https://github.com/kadas-albireo/kadas-albireo2
     - Swiss military GIS application based on QGIS

3. GDAL (MIT/X)
     - https://gdal.org
     - Geospatial Data Abstraction Library

IMAGERY DATA LICENSES

Satellite imagery accessed through this plugin is provided by various sources
under the AWS Open Data Program. Each dataset has its own license terms:

- Sentinel-2: Copernicus Sentinel Data (European Space Agency)
    Terms:
    https://scihub.copernicus.eu/twiki/do/view/SciHubWebPortal/TermsConditions

- Landsat: USGS/NASA (Public Domain)
    Terms:
    https://www.usgs.gov/information-policies-and-instructions/copyrights-and-credits

- Vantor Open Data Program: Creative Commons BY-NC-SA 4.0
    Terms: https://vantor.com/company/open-data-program/

- Other datasets: See individual STAC metadata for license information

ATTRIBUTION

This plugin was inspired by and builds upon concepts from:

- qgis-maxar-plugin by Qiusheng Wu (MIT License)
    https://github.com/opengeos/qgis-maxar-plugin

- kadas-vantor-plugin by Michael Lanini (MIT License)
    https://github.com/mlanini/kadas-vantor-plugin

DISCLAIMER

THE IMAGERY DATA IS PROVIDED BY THIRD PARTIES. THE AUTHORS OF THIS SOFTWARE
MAKE NO REPRESENTATIONS OR WARRANTIES REGARDING THE ACCURACY, COMPLETENESS,
OR SUITABILITY OF ANY IMAGERY DATA ACCESSED THROUGH THIS PLUGIN.
"""


def disclaimer_already_accepted() -> bool:
    """Return True when the user has previously accepted and stored consent."""
    return QgsSettings().value(_SETTINGS_KEY, False, type=bool)


def reset_disclaimer() -> None:
    """Clear persisted acceptance flag."""
    QgsSettings().remove(_SETTINGS_KEY)


class DisclaimerDialog(QDialog):
    """Modal dialog presenting liability disclaimer and MIT license."""

    def __init__(self, parent=None):
        super().__init__(parent, Qt.Dialog | Qt.WindowCloseButtonHint)
        self.setWindowTitle("KADAS Altair - Terms of Use and License")
        self.setMinimumWidth(620)
        self.setMinimumHeight(540)
        self._build_ui()

    def _build_ui(self) -> None:
        root = QVBoxLayout(self)
        root.setSpacing(10)

        title = QLabel(
            "Please read and accept the following before continuing"
        )
        title_font = QFont()
        title_font.setPointSize(10)
        title_font.setBold(True)
        title.setFont(title_font)
        title.setAlignment(Qt.AlignCenter)
        root.addWidget(title)

        root.addWidget(self._section_label("1 - Limitation of Liability"))
        disclaimer_label = QLabel(_DISCLAIMER_TEXT)
        disclaimer_label.setWordWrap(True)
        disclaimer_label.setTextFormat(Qt.RichText)
        disclaimer_label.setStyleSheet(
            "QLabel { background:#f9f9f9; padding:8px; border:1px solid #ccc; "
            "border-radius:4px; font-size:10px; }"
        )
        root.addWidget(disclaimer_label)

        self._cb_disclaimer = QCheckBox(
            "I understand and accept that I am solely responsible for any "
            "operational use of this software."
        )
        self._cb_disclaimer.setStyleSheet("font-weight: bold;")
        self._cb_disclaimer.stateChanged.connect(self._update_ok_button)
        root.addWidget(self._cb_disclaimer)

        sep = QFrame()
        sep.setFrameShape(QFrame.HLine)
        sep.setFrameShadow(QFrame.Sunken)
        root.addWidget(sep)

        root.addWidget(self._section_label("2 - Software License (MIT)"))
        license_edit = QTextEdit()
        license_edit.setReadOnly(True)
        license_edit.setPlainText(_LICENSE_TEXT)
        license_edit.setFixedHeight(140)
        license_edit.setStyleSheet(
            "QTextEdit { background:#f0f4f8; font-family: Consolas, "
            "monospace; "
            "font-size: 10px; border:1px solid #ccc; "
            "border-radius:4px; }"
        )
        root.addWidget(license_edit)

        self._cb_license = QCheckBox(
            "I have read and accept the terms of the MIT License."
        )
        self._cb_license.setStyleSheet("font-weight: bold;")
        self._cb_license.stateChanged.connect(self._update_ok_button)
        root.addWidget(self._cb_license)

        sep2 = QFrame()
        sep2.setFrameShape(QFrame.HLine)
        sep2.setFrameShadow(QFrame.Sunken)
        root.addWidget(sep2)

        self._cb_remember = QCheckBox(
            "Remember my acceptance and do not show this dialog again"
        )
        self._cb_remember.setStyleSheet("color: #555; font-size: 10px;")
        root.addWidget(self._cb_remember)

        self._button_box = QDialogButtonBox(
            QDialogButtonBox.Ok | QDialogButtonBox.Cancel
        )
        self._ok_btn = self._button_box.button(QDialogButtonBox.Ok)
        self._ok_btn.setText("Accept and Continue")
        self._ok_btn.setEnabled(False)
        self._button_box.accepted.connect(self._on_accept)
        self._button_box.rejected.connect(self.reject)
        root.addWidget(self._button_box)

    @staticmethod
    def _section_label(text: str) -> QLabel:
        label = QLabel(text)
        font = QFont()
        font.setPointSize(9)
        font.setBold(True)
        label.setFont(font)
        return label

    def _update_ok_button(self) -> None:
        accepted = (
            self._cb_disclaimer.isChecked() and self._cb_license.isChecked()
        )
        self._ok_btn.setEnabled(accepted)

    def _on_accept(self) -> None:
        if self._cb_remember.isChecked():
            QgsSettings().setValue(_SETTINGS_KEY, True)
        self.accept()
